### ISSUE TITLE
pkg_resources.DistributionNotFound: swift3

### ISSUE THREAD

**Issue by shooding** [kahing/docker-swift#13]
Running on Mac OS X with boot2docker.

Error occurs while running
docker run -P -v <path>:/swift/nodes -t kahing/docker-swift

,which blocks up later processes.
After removing swift3 from swift/proxy-server.conf  pipeline, it works.

**Comment by shooding** [comment]
I've created a pull request to fix this.

**Comment by kahing** [comment]
closed by #14
